// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdbnhb-M3tp7At2nP62_5UAO1JFUFxrio',
    appId: '1:608924512048:web:7ef3e29a712ab4bc5c22f5',
    messagingSenderId: '608924512048',
    projectId: 'loginfetin',
    authDomain: 'loginfetin.firebaseapp.com',
    storageBucket: 'loginfetin.firebasestorage.app',
    measurementId: 'G-1V5C4YHBXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmYrQGT8kE8BK9ifmZ5XcSo5lyoMJJQhI',
    appId: '1:608924512048:android:b5c764ff9e04e5e25c22f5',
    messagingSenderId: '608924512048',
    projectId: 'loginfetin',
    storageBucket: 'loginfetin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZZhpWOhbCRoegqFG8bMtba6dJ5QImfo4',
    appId: '1:608924512048:ios:49ac82510d2ee0f95c22f5',
    messagingSenderId: '608924512048',
    projectId: 'loginfetin',
    storageBucket: 'loginfetin.firebasestorage.app',
    iosClientId: '608924512048-v51qr7899d7fo0j0b38jvaqpfalc7gkv.apps.googleusercontent.com',
    iosBundleId: 'com.example.socorroFacil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZZhpWOhbCRoegqFG8bMtba6dJ5QImfo4',
    appId: '1:608924512048:ios:49ac82510d2ee0f95c22f5',
    messagingSenderId: '608924512048',
    projectId: 'loginfetin',
    storageBucket: 'loginfetin.firebasestorage.app',
    iosClientId: '608924512048-v51qr7899d7fo0j0b38jvaqpfalc7gkv.apps.googleusercontent.com',
    iosBundleId: 'com.example.socorroFacil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdbnhb-M3tp7At2nP62_5UAO1JFUFxrio',
    appId: '1:608924512048:web:160ea734f0284ac25c22f5',
    messagingSenderId: '608924512048',
    projectId: 'loginfetin',
    authDomain: 'loginfetin.firebaseapp.com',
    storageBucket: 'loginfetin.firebasestorage.app',
    measurementId: 'G-1RMPRG61PH',
  );
}
